# Generated by Django 4.2 on 2023-04-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('content_html', models.TextField()),
            ],
            options={
                'db_table': 'paid_content',
            },
        ),
    ]
